{{- if .Values.baseImageCredentials -}}
apiVersion: v1
kind: Secret
metadata:
    name: knative-base-registry-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "baseImagePullSecret" . }}
{{- end -}}
