apiVersion: v1
kind: Service
metadata:
  name: {{ include "aas-backend.fullname" . }}
  labels: {{- include "aas-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "aas-backend.selectorLabels" . | nindent 4 }}
