{{- if .Values.imagePullSecrets -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-registry-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}