# Use this if k8s cluster unable to dynamically provision storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aas-minio-pv
  namespace: ai-appstore
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  storageClassName: aas-minio
  hostPath:
    path: "/home/dh/minio"
