apiVersion: v1
kind: Namespace
metadata:
  name: ai-appstore
  labels:
    webhooks.knative.dev/exclude: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: inference-engine
---
apiVersion: v1
kind: Namespace
metadata:
  name: kourier-system
  labels:
    networking.knative.dev/ingress-provider: kourier
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: net-kourier
    app.kubernetes.io/version: "1.8.1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: "1.8.3"
