apiVersion: v1
appVersion: 3.4.0
description: Helm chart to ensure Emissary CRDS are installed
home: https://www.getambassador.io/
icon: https://www.getambassador.io/images/logo.png
keywords:
- api gateway
- ambassador
- datawire
- envoy
- emissary
- emissary ingress
maintainers:
- email: markus@maga.se
  name: flydiverny
- email: flynn@datawire.io
  name: kflynn
- email: nkrause@datawire.io
  name: nbkrause
- email: lukeshu@datawire.io
  name: lukeshu
name: emissary-ingress
sources:
- https://github.com/datawire/ambassador
- https://github.com/prometheus/statsd_exporter
version: 8.4.0
