{{- if .Values.imageCredentials -}}
apiVersion: v1
kind: Secret
metadata:
    name: ie-registry-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
