{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aas-frontend.serviceAccountName" . }}
  namespace: ai-appstore
  labels:
    {{- include "aas-frontend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aas-frontend.serviceAccountName" . }}-system-role
  namespace: ai-appstore
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - anyuid
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aas-frontend.serviceAccountName" . }}-system-rolebinding
  namespace: ai-appstore
subjects:
  - kind: ServiceAccount
    name: {{ include "aas-frontend.serviceAccountName" . }}
    namespace: ai-appstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aas-frontend.serviceAccountName" . }}-system-role
  namespace: ai-appstore