apiVersion: v1
kind: Service
metadata:
  name: {{ include "aas-frontend.fullname" . }}
  labels: {{- include "aas-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "aas-frontend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aas-frontend.fullname" . }}-nodeport
  labels: {{- include "aas-frontend.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP
      name: http
  selector: {{- include "aas-frontend.selectorLabels" . | nindent 4 }}
